name = "PolynomialBases"
uuid = "c74db56a-226d-5e98-8bb0-a6049094aeea"
author = ["Hendrik Ranocha"]
version = "0.4.6"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
FastTransforms = "057dd010-8810-581a-b7be-e3fc3b93f78c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
ArgCheck = "1, 2.0"
FastGaussQuadrature = "0.4.2"
FastTransforms = "0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.10, 0.11"
Parameters = "0.12"
Requires = "0.5.2, 1"
SpecialFunctions = "0.7, 0.8, 0.9, 0.10"
julia = "0.7, 1"

[extras]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
SymEngine = "123dc426-2d89-5057-bbad-38513e3affd8"
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["InteractiveUtils", "StaticArrays", "SymEngine", "SymPy", "Test"]
