name = "PolynomialBases"
uuid = "c74db56a-226d-5e98-8bb0-a6049094aeea"
author = ["Hendrik Ranocha"]
version = "0.4.24"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SimpleUnPack = "ce78b400-467f-4804-87d8-8f486da07d0a"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
ArgCheck = "2.0"
AutoHashEquals = "0.2, 1, 2"
FFTW = "1"
FastGaussQuadrature = "0.4.3, 0.5, 1"
Requires = "1"
SimpleUnPack = "1"
SpecialFunctions = "1, 2"
julia = "1.6"
